CREATE PROC FI_SP_ResetTables
AS
BEGIN
	DELETE FROM BENEFICIARIOS;
	DELETE FROM CLIENTES;

	DBCC CHECKIDENT ('CLIENTES', RESEED, 0);
	DBCC CHECKIDENT ('BENEFICIARIOS', RESEED, 0);

	PRINT('Tabelas resetadas!');
END