CREATE PROC FI_SP_VerificaCliente
	@CPF VARCHAR(11),
	@Id  BIGINT = 0
AS
BEGIN 
	If (ISNULL(@Id, 0) = 0)
		SELECT ID FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF
	ELSE
		SELECT ID FROM CLIENTES WITH(NOLOCK) WHERE CPF = @CPF AND ID <> @Id
END