CREATE PROC FI_SP_DelBeneficiario
	@ID VARCHAR(MAX),
	@IDCLIENTE BIGINT
AS
BEGIN
	DECLARE @SQL NVARCHAR(MAX);
	
	SET @SQL = 'DELETE BENEFICIARIOS WHERE ID NOT IN (' + @ID + ') AND IDCLIENTE = ' + CAST(@IDCLIENTE AS VARCHAR);
	
	EXECUTE SP_EXECUTESQL @SQL;
END