CREATE PROC FI_SP_PesqBeneficiario
	@IDCLIENTE BIGINT
AS
BEGIN
	DECLARE @SCRIPT NVARCHAR(MAX)
	DECLARE @CAMPOS NVARCHAR(MAX)

	SET @CAMPOS = '@IdCliente BIGINT'
	SET @SCRIPT = 'SELECT ID, IDCLIENTE, NOME, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IdCliente ORDER BY NOME'
	
	EXECUTE SP_EXECUTESQL @SCRIPT, @CAMPOS, @IDCLIENTE

END