CREATE PROC FI_SP_VerificaBeneficiario
	@CPF		VARCHAR(11),
	@IDCLIENTE  BIGINT,
	@ID			BIGINT = 0
AS
BEGIN 
	IF (ISNULL(@ID,0) = 0)
		SELECT ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE
	ELSE
		SELECT ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE CPF = @CPF AND IDCLIENTE = @IDCLIENTE AND ID <> @ID
END